import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import SvgWave from '../layered-waves-haikei.svg'
import Card from '../components/Card'
import Modal from '../components/Modal'

const Home: NextPage = () => {
  const genres = [{
    title: 'POP'
  }, {
    title: 'ROCK'
  },{
    title: 'LO-FI'
  },{
    title: 'CLASSICA'
  }]
  return (
    <div className={styles.container}>
      <Head>
        <title>Weatherly</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>
        Seja bem-vindo ao Weatherly!
      </h1>
      <p className={styles.subtitle}>
        <a>Climatize</a> suas músicas favoritas
      </p>
      <Modal type='genre'/>
    {/* <Modal/> */}
    </div>
  )
}

export default Home
