import { useRouter } from 'next/router'
import React, { useEffect, useState } from 'react'
import Modal from '../components/Modal'
import Head from 'next/head'
import axios from 'axios';
import styles from '../styles/Songs.module.css'

const songs = () => {
    const [data, setData] = useState<object>()
    const options:any = {
        method: 'GET',
        url: 'https://shazam.p.rapidapi.com/search',
        params: {term: 'pop', locale: 'en-US', offset: '0', limit: '5'},
        headers: {
          'x-rapidapi-host': 'shazam.p.rapidapi.com',
          'x-rapidapi-key': 'aec302c28emshc79ebaef6348943p1f1067jsnf62c80ac1a1d'
        }
      };
    function successFunction(position: any) {
        var lat = position.coords.latitude;
        var long = position.coords.longitude;
        console.log('Your latitude is :'+lat+' and longitude is '+long);
        const proxy =  "https://cors-anywhere.herokuapp.com/";
        const api = `api.openweathermap.org/data/2.5/weather?lat=-22.9897&lon=-47.479&units=metric&appid=49549acbaf3ad5434ef335141b66fefb`;
       fetch(api).then((res) => res.json()).then(data =>{
        console.log({data});       
})
    }
    function errorFunction() {
        console.log('erro');
    }
    useEffect(() => {
        axios.request(options).then(function (response) {
            setData(response.data);
        }).catch(function (error) {
            console.error(error);
        });
    }, [])
    useEffect(() => {
        console.log(data);  
    }, [data])
    const router = useRouter()
    return (
        <div>
            <Head>
                <title>Weatherly</title>
                <meta name="description" content="Generated by create next app" />
                 <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1 onClick={() => router.push("/")} className={styles.title}>Weatherly</h1>
            <Modal type='song' options={data}/>
        </div>
    )
}

export default songs
